import type { Metadata } from 'next'
import { Pathway_Extreme } from 'next/font/google'
import '@/styles/globals.css'
import { menuItems, footerItems } from '@/constants'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const PathWayXtreme = Pathway_Extreme({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={[PathWayXtreme.className, 'page-wrapper'].join(' ')}>
        <Header menuData={menuItems} />
        {children}
        <Footer footerItems={footerItems} />
      </body>
    </html>
  )
}
